var routes = {
  "about"                               : "about/about.html",
  "archives"                            : "about/archives.html",
  "developmentroadmap"                  : "about/roadmap.html",
  "news"                                : "about/news.html",
  "sparerib"                            : "about/sparerib.html",
  "support"                             : "support/support.html",
  "faq"                                 : "support/faq.html",
  "help"                                : "support/help.html",
  "librarians"                          : "support/librarians.html",
  "sitemap"                             : "about/sitemap.html",
  "terms"                               : "about/termsofuse.html",
  "britishlibrary/sparerib/ethicaluse"  : "sparerib/about/ethicaluse.html",
  "accessibility"                       : "about/accessibility.html",
  "privacy"                             : "about/privacy.html",
  "cookies"                             : "about/cookies.html",
  "surveys"                              : "about/surveys.html",
  "quickref"                            : "support/quickref.html",
  "browser"                             : "about/browser.html"     
};
