var routes = {
  "about"                               : "about/about.html",
  "archives"                            : "about/archives.html",
  "developmentroadmap"                  : "about/roadmap.html",
  "news"                                : "about/news.html",
  "sparerib"                            : "about/sparerib.html",
  "support"                             : "support/support.html",
  "faq"                                 : "support/faq.html",
  "help"                                : "support/help.html",
  "librarians"                          : "support/librarians.html",
  "sitemap"                             : "about/sitemap.html",
  "terms"                               : "about/termsofuse.html",
  "britishlibrary/sparerib/ethicaluse"  : "sparerib/about/ethicaluse.html",
  "accessibility"                       : "about/accessibility.html",
  "privacy"                             : "about/privacy.html",
  "cookies"                             : "about/cookies.html",
  "features"              				: "support/features.html",
  "surveys"                             : "about/surveys.html",
  "quickref"                            : "support/quickref.html",
  "titlelist"                           : "about/titlelist.html",
  "englishlit"                  		: "features/englishlit.html",
  "history"                  			: "features/history.html",
  "browser"                             : "about/browser.html"     
};
